# Generated by Django 4.0.2 on 2022-02-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoclasses',
            name='courseNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='djangoclasses',
            name='duration',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
